# Generated by Django 3.0.8 on 2020-07-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True, verbose_name='HTML page')),
            ],
            options={
                'verbose_name': 'HTML page',
                'verbose_name_plural': 'HTML pages',
            },
        ),
        migrations.CreateModel(
            name='WorkMonth',
            fields=[
                ('month', models.SmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Month')),
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='Month id')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
            },
        ),
        migrations.CreateModel(
            name='WorkDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.WorkMonth')),
            ],
            options={
                'verbose_name': 'Date',
                'verbose_name_plural': 'Dates',
            },
        ),
        migrations.CreateModel(
            name='FrontText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='HTML text')),
                ('text_name', models.CharField(max_length=20, unique=True, verbose_name='HTML text name')),
                ('front_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.FrontPage')),
            ],
        ),
        migrations.CreateModel(
            name='FrontImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='HTML image')),
                ('image_name', models.CharField(max_length=20, unique=True, verbose_name='HTML image name')),
                ('front_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.FrontPage')),
            ],
        ),
    ]
