# Generated by Django 3.0.8 on 2020-07-20 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9, verbose_name='Phone')),
                ('first_name', models.CharField(max_length=25, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('delivery_date', models.DateField(verbose_name='Delivery date')),
                ('delivery_time', models.SmallIntegerField(choices=[(0, '09-10'), (1, '10-11'), (2, '11-12'), (3, '12-13'), (4, '13-14'), (5, '14-15'), (6, '15-16'), (7, '16-17'), (8, '17-18'), (9, '18-18.30')], verbose_name='Delivery time')),
                ('address', models.CharField(max_length=60, verbose_name='Address')),
                ('comment', models.TextField(blank=True, max_length=60, null=True, verbose_name='Comment')),
                ('payment', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Card'), (2, 'Online')], verbose_name='Payment method')),
                ('status', models.BooleanField(default=0, verbose_name='Confirmed')),
                ('discount', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount')),
                ('order_price', models.FloatField(default=0, verbose_name='Order price')),
                ('order_items', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Pizza', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
