# Generated by Django 3.0.8 on 2020-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Filter')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Pizza name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price')),
                ('text_short', models.CharField(max_length=100, verbose_name='Short text')),
                ('text_long', models.TextField(verbose_name='Long text')),
                ('category', models.SmallIntegerField(choices=[(1, 'Category 1'), (2, 'Category 2'), (3, 'Category 3'), (4, 'Category 4')], verbose_name='Category')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('filter', models.ManyToManyField(to='catalog.Filter', verbose_name='Filter')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
                'ordering': ('category', 'name'),
            },
        ),
    ]
